### ISSUE TITLE
Create a KVDB Clone over the Network

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#15]
Say I boot an instance of my database in a brand new datacenter, is there a better way to transmit the entire KVDB over the network to this new database instance than iterating over and serializing every key/value pair?

**Comment by smoyergh** [comment]
If the volume you configured for your mpool is on some sort of shared storage, like an AWS EBS volume, you could snapshot the volume and use the native shared storage mechanisms to transfer/replicate it, mount it on the receiving system, and then use "mpool activate".

Ideally you should shutdown the application using the KVDB before moving/replicating it this way so that you are transferring the KVDB in a consistent state.  But even if you don't it will recover properly on the receiving end, since this is equivalent to a crash recovery.

**Comment by victorstewart** [comment]
okay thanks! i'm pointed in the right direction now.

i'll take a snapshot at a timestamp, compress it, send it and then stream all new changes from that timestamp forward to complete the synchronization.

**Comment by victorstewart** [comment]
This seems like a pretty decent tutorial for how to get this done: [https://serverfault.com/a/920246/513064](https://serverfault.com/a/920246/513064)
