### ISSUE TITLE
Put perform much less than Get.

### ISSUE THREAD

**Issue by jliang000** [hse-project/hse#9]
We modified the sample code to some bench test on one nvme device. My setup composed one kvdb for each raw device, two kvs instances, put 500k dummy objects (512k data value each) follow with reading back. We record 2GBps get throughput, but only 270MBps for put. Is that expected or anything we might miss here.  fio seq io on the devices shows around 2GBps for both reading and writing.

**Comment by smoyergh** [comment]
Using YCSB as a load generator, a 2TB load phase (which is basically puts) runs at ~1GBps, and Workload C (which is basically gets) runs at 1.7GBps for a common HW config we use in our lab.  The throughput depends heavily on the HW config, workload generator, and KVDB/KVS config, but that at least provides a ratio of put vs get throughput that we see in similar benchmarks.

As a start point, can you provide more details on your HW and OS, dur_intvl_ms setting for the KVDB, and KVS configuration.

@davidboles what else do you want to see?

**Comment by davidboles** [comment]
Beyond the items requested by @smoyergh, the specific modified sample code that generates the observed behavior would be helpful to root cause any issues ASAP.

**Comment by jliang000** [comment]
There is the config I tested.

mpool create nvme0_db /dev/nvme0n1 capsz=32
# hse kvdb list -v
kvdbs:
- name: nvme0_db
  label: raw
  kvslist:
    - nvme0_db/kvs0
    - nvme0_db/kvs1

there is a very simple bench test code uploaded here for reference. you can launch as below (rename txt to c).  Please help check what you get or any problem of the test. Thanks

./hse_bench nvme0_db kvs 2 500000 512 0

[hse_bench.txt](https://github.com/hse-project/hse/files/4663744/hse_bench.txt)

**Comment by davidboles** [comment]
I've reproduced the behavior you are experiencing and root caused the issue. It isn't the easiest thing to explain so please bear with me.

1. The HSE engine conducts various operations on behalf of the client w/o the client directly invoking these operations. For example, there is a default "sync" interval to flush data to media. There are also background maintenance operations to keep the search data structures compact.

2. The HSE engine starts off with client "puts" throttled and tunes this throttling as it discovers how fast the I/O subsystem beneath it can run. It also adapts as the client workload changes. Because the performance range of I/O subsystems is very large (in terms of both bandwidth and latency distribution as a function of queue depth), this auto-tuning takes an extended period of time (e.g., 200 seconds).

3. If I disable the throttling (explained below), the application runs much faster (~1.9GB/sec for the puts on the system I was using), but this has created maintenance that needs to be done. Here is the output from the run I performed:

```
$ ./workload mp1 kvs 2 500000 512 0
kvs0 th 0 Timestamp 1590590959 key prefix key000 offset 6
kvs1 th 1 Timestamp 1590590959 key prefix key010 offset 6
... Write finished 450000 ops                              
kvs1 th 1: Timestamp 1590591091 Write done --- nr_req 500000, bs 512 KB, bw 1941152.00 KBps

kvs0 th 0: Timestamp 1590591092 Write done --- nr_req 500000, bs 512 KB, bw 1926683.00 KBps
... Read finished 450000 ops                              
kvs0 th 0: Timestamp 1590591272 Read done --- nr_req 500000, bs 512 KB, bw 1423984.00 KBps

kvs1 th 1: Timestamp 1590591274 Read done --- nr_req 500000, bs 512 KB, bw 1400452.00 KBps
```

4. The most accurate way to perform your test would be to modify your application to perform its put operations as fast as it can (which will accelerate as the system tunes itself) for 220 seconds and then (within the same process) do the time sampling over some meaningful interval. Note - the 220 seconds is a property of your system.

The easiest way to run with throttling disabled is to load a "params" config file. I have attached an altered version of your code and such a configuration file. Rename hse_bench.txt to hse_bench.c and workload.txt to workload.yml.

Also, it's worth pointing out that the sample code in the repo has errors w/r to how the return codes from the HSE KVDB API work. When the samples were written the return codes were just errno's. However, they are now hse_err_t's which are very much not errno's. You can convert them to errno's (using the hse_err_to_errno() function) but that destroys information. You can get a string representation of the error using hse_err_to_string(). You can't call strerror() on an hse_err_t and get a meaningful result. In the areas where I've modified your code you can see how to use the hse_err_t's.

We will be working to refine the self-tuning in future versions of HSE to shorten the ramp time and will update the Wiki to cover this topic.

[hse_bench.txt](https://github.com/hse-project/hse/files/4689869/hse_bench.txt)
[workload.txt](https://github.com/hse-project/hse/files/4689878/workload.txt)

**Comment by jliang000** [comment]
Thanks for the tips. It works, just the memory usage climbs up quickly. I have to reduce the io size or do the time-wise control on the bench as you mentioned.

**Comment by smoyergh** [comment]
Regarding memory, what you are very likely seeing is HSE indexing data in the page cache.  This indexing data is never dirty, so the OS can reclaim it at any time without performing I/O.  If this is what's happening, then it is by design.  If you provide memory stats (from vmstat or similar) we can verify for you.

**Comment by neelima84** [comment]
As @davidboles mentioned, client puts are throttled at the beginning and the mechanism auto-tunes over time based on how fast the I/O subsystem can keep up. It may take a while to ramp up.

Client puts are also slowed down to ensure memory usage remains below a threshold. When throttling is disabled, the memory usage may ramp up quickly because there is nothing to slow down the client puts. The in memory component of the storage engine can continue to accept puts even if the I/O subsystem is lagging behind. The problem is exacerbated with large value sizes.

It is preferable to run the test with throttling enabled, for a longer duration and measure performance factoring in the initial ramp up time.
